## defaults for _all_ profiles
[default]
address = "0.0.0.0"
limits = { form = "64 kB", json = "1 MiB" }
port = 8000


## set only when compiled in release mode, i.e, `cargo build --release`
[release]
port = 443
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvDFSafdBi2QJxBVHQk="